### - разделитель для запросов


GET {{url}}/api/posts?lastPost=0&step=3
Authorization: Basic vasya secret
###

POST {{url}}/api/posts
Authorization: Basic vasya secret
Content-Type: application/json

{
  "id": 0,
  "authorId": 1,
  "authorName": "vasya",
  "content": "Last post",
  "media": null
}

###

POST {{url}}/api/users
Authorization: Basic vasya secret
Content-Type: application/json

{
  "id": 0,
  "name": "Ivan",
  "username": "ivan",
  "password": "ivan",
  "email": "ivan@mail.ru",
  "photo": null
}

###

GET {{url}}/api/users/me
Authorization: Basic vasya secret

###

DELETE {{url}}/api/posts/1
Authorization: Basic vasya secret

###

DELETE {{url}}/api/posts/2
Authorization: Basic vasya secret




###



POST {{url}}/api/posts/2/likes

###

DELETE {{url}}/api/posts/1/likes

###

GET {{url}}/api/posts?q=First

###

DELETE {{url}}/api/posts/hello

###

POST {{url}}/api/files/multipart
Content-Type: multipart/form-data; boundary=WebApp

--WebApp
Content-Disposition: form-data; name="file"; filename="panda.jpd"
Content-Type: image/jpeg

< ./java.jpg
--WebApp--

###

POST {{url}}/api/files/bytes
Content-Type: application/octet-stream

< ./java.jpg

###