### - разделитель для запросов


GET {{url}}/api/posts?lastPost=0&step=3

###
GET {{url}}/api/posts?firstPostId=3

###

POST {{url}}/api/posts
Content-Type: application/json

{
  "id": 0,
  "authorId": 1,
  "authorName": "vasya",
  "content": "Last post",
  "media": null
}

###

POST {{url}}/api/posts
Content-Type: application/json

{
  "id": 0,
  "content": "Dislike this stuff! I'm disagree with author!",
  "media": null
}

###

DELETE {{url}}/api/posts/1

###

POST {{url}}/api/posts/2/likes

###

DELETE {{url}}/api/posts/1/likes

###

GET {{url}}/api/posts?q=First

###

DELETE {{url}}/api/posts/hello

###

POST {{url}}/api/files/multipart
Content-Type: multipart/form-data; boundary=WebApp

--WebApp
Content-Disposition: form-data; name="file"; filename="panda.jpg"
Content-Type: image/jpeg

< ./java.jpg
--WebApp--

###

POST {{url}}/api/files/bytes
Content-Type: application/octet-stream

< ./java.jpg

###